### ISSUE TITLE
Incorrect blackbox

### ISSUE THREAD

**Issue by DeeNaxic** [isabellaedwards/8g#1]
This just prints it. You should print a true or false, to check that all values are correct. Don't rely on the user to MANUALLY INSPECTING EACH TEST CASE, to figure out if it's right or not.

in: https://github.com/isabellaedwards/8g/blob/master/8g0.fsx

Instead do something like (pseudo code)

bool BlackBoxTest_01 ()
{
  return (monday.GetInt() == 1 && tuesday.Getint() == 2 && ...);
}

**Comment by isabellaedwards** [comment]
I see, tak! Men hvordan ville du vise, at den returnerer null ved andet input? Fx -1, 0 og 8
